### ISSUE TITLE
printing.txt and tcp.txt missing

### ISSUE THREAD

**Issue by marta312** [ryanpennings/RTDE_UR#1]
Hi Ryan, thank you for sharing this interface!
I am trying to run it on URSim, everything seems to work but the phyton program return an error related to the file "printing.txt". I checked in the code and it seems it will look also to "tcp.txt". These files are not present in the cloned repository.
I imagine these are the list of points and the tcp configuration.

Could you please provide some indication on how to create these files?
Thank you again!

**Comment by ryanpennings** [comment]
Sorry for the very late reply, I didn't see this...
The txt files you can create yourself, they are in the following format: (sorry I can't find them anymore)

#### Printing.txt

0,1,2,3,4,5 are point locations
x,y,z,rx,ry,rz
6 is speed in m/s
7 is zone in m

format:
x,y,z,rx,ry,rz,speed,zone

each line is a new point
Which would look like this:
*******************************
10,20,30,1,1,0,0.1,0.01
10,22,30,1,1,0,0.1,0.01 
10,24,30,1,1,0,0.1,0.01 
*******************************  

#### tcp.txt

0,1,2,3,4,5 are point locations for tcp
x,y,z,rx,ry,rz
6 weight in kg
7,8,9 are Centre of Gravity

format:
x,y,z,rx,ry,rz,weight,COGx,COGy,COGz

this is a single line
*******************************   
49.4,120,66.6,0,1,0,5,20,80,30
*******************************   

rx,ry,rz are a rotation vector in radians.
