### ISSUE TITLE
Robot motor currents and other RTDE outputs

### ISSUE THREAD

**Issue by ghost** [ryanpennings/RTDE_UR#4]
Hello,

I am working on the robot (UR10 CB3 series) data received through RTDE for quite a few months now. My objective is to understand the source of the values for the outputs received through RTDE. as well as the meaning and relationship between the outputs.

For example, the values under “joint_temperatures_0” are received from the temperature sensor present in the “joint_0” of the robot.

I already have found out, that the output “joint_control_ouput_0” is the target current for the motor in “joint_0”. This is true because the values under “actual_current_0” and “joint_control_output_0” are the same. Whereas there is another output called “target_current_0”, for which there is not much information provided and therefore I have the following questions:

1. What is the meaning for “target_current_0”?
2. What is the theoretical relationship between “target_current_0”, “actual_current_0” and “target_control_output_0” (w.r.t the joint motor)? (I would be glad to have a look at some detailed documentation if anybody have come across it so far)
Apart from the above questions, I also have another set of the following question:

1. Are the values under “actual_TCP_force_0” calculated or estimated from integrated sensors (for CB3 series)?
2. Are the values under “actual_tool_accelerometer” from an accelerometer at TCP?
3. How are the values under “target_moment” calculated? if these are calculated using inverse dynamics (https://en.wikipedia.org/wiki/Inverse_dynamics), what will be the linear acceleration w.r.t the output data from RTDE?
4. Are the values under “target_TCP_speed” and “actual_TCP_speed” calculated using the typical time derivative of “target_TCP_pose” and “actual_TCP_pose” respectively or using the Jacobian matrix?
5. Are the values under “tool_temperature” coming from a separate temperature sensor (apart from the temperature sensors at each robot joint) at the tool head?

Thank you in advance

**Comment by ryanpennings** [comment]
Please refer to documentation on the Universal Robots website.
